import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'package:provider_playgroud/services/firebase_auth_service.dart';
import 'package:provider_playgroud/services/firebase_storage_service.dart';
import 'package:provider_playgroud/services/firestore_service.dart';

/// Used to create user-dependant objects that need to be accessible by all widgets.
/// This widget should live above the [MaterialApp].
/// See [AuthWidget], a descendant widget that consumes the snapshot generated by this builder.
class AuthWidgetBuilder extends StatelessWidget {
  final Widget Function(BuildContext, AsyncSnapshot<CurrentUser?>) builder;

  const AuthWidgetBuilder({Key? key, required this.builder}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    final authService =
        Provider.of<FirebaseAuthService>(context, listen: false);
    print('AuthWidgetBuilder rebuild');
    return StreamBuilder<CurrentUser?>(
      stream: authService.onAuthStateChanged,
      builder: (context, snapshot) {
        print('StreamBuilder: ${snapshot.connectionState}');
        final CurrentUser? user = snapshot.data;
        if (user != null) {
          return MultiProvider(
            providers: [
              Provider<CurrentUser>.value(value: user),
              Provider<FirestoreService>(
                create: (_) => FirestoreService(uid: user.uid),
              ),
              Provider<FirebaseStorageService>(
                create: (_) => FirebaseStorageService(uid: user.uid),
              ),
            ],
            child: builder(context, snapshot),
          );
        }
        return builder(context, snapshot);
      },
    );
  }
}
